# This workflow will install Python dependencies and bundle using Pyinstaller with a single version of Python

name: Bundle using Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies (pyinstaller, requirements.txt)
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Bundle with Pyinstaller
      run: |
        pyinstaller run.py -F -n heroed
